- DotNetty.sln
- src/DotNetty.Codecs/CorruptedFrameException.cs
- src/DotNetty.Codecs/DotNetty.Codecs.csproj
- src/DotNetty.Codecs/LengthFieldBasedFrameDecoder.cs
- src/DotNetty.Codecs/TooLongFrameException.cs
- test/DotNetty.Codecs.Tests/DotNetty.Codecs.Tests.csproj
- test/DotNetty.Codecs.Tests/Properties/AssemblyInfo.cs
- test/DotNetty.Codecs.Tests/packages.config
Implemented the following classes:
- LengthFieldBaseFrameDecoder
- TooLongFrameException
- CorruptedFrameException
Added the following projects:
- DotNetty.Codecs.Tests
> implemented LengthFieldBaseFrameDecoder

- CONTRIBUTING.MD
Based on https://github.com/akkadotnet/akka.net/blob/dev/CONTRIBUTING.md
Updated links to link to our C# coding style guidelines and practices.
Gave attribution to both Akka.NET and NancyFx in the footer.
> Added a contributing procedure file

- src/DotNetty.Buffers/AbstractByteBuffer.cs
- src/DotNetty.Common/Concurrency/IEventExecutor.cs
- src/DotNetty.Common/Concurrency/SingleThreadEventExecutor.cs
- src/DotNetty.Transport/Channels/PausableChannelEventExecutor.cs
- test/DotNetty.Buffers.Tests/AbstractByteBufferTests.cs
- test/DotNetty.Tests.End2End/End2EndTests.cs
Adds IEventExecutor.Schedule overload with 2 state parameters per #14
Fix async stream reading to AbstractByteBuffer per #15
> extra IEventExecutor.Schedule overload, async stream reading fix

- src/DotNetty.Transport/Channels/Sockets/TcpSocketChannel.cs
Corrects TcpSocketChannel.DoReadBytes to properly respond on graceful socket closure by the other party (see #26).
> Graceful socket closure fix (#26)

- RELEASE_NOTES.md
- src/DotNetty.Buffers/DotNetty.Buffers.nuspec
- src/DotNetty.Codecs.Mqtt/DotNetty.Codecs.Mqtt.nuspec
- src/DotNetty.Codecs/DotNetty.Codecs.nuspec
- src/DotNetty.Common/DotNetty.Common.nuspec
- src/DotNetty.Handlers/DotNetty.Handlers.nuspec
- src/DotNetty.Transport/DotNetty.Transport.nuspec
- src/SharedAssemblyInfo.cs
... in preparation of nuget release
> fixing nuget specs, 0.1.3 release notes

- DotNetty.sln
- examples/Echo.Client/App.config
- examples/Echo.Client/ClientSettings.cs
- examples/Echo.Client/Echo.Client.csproj
- examples/Echo.Client/EchoClientHandler.cs
- examples/Echo.Client/Program.cs
- examples/Echo.Client/Properties/AssemblyInfo.cs
- examples/Echo.Server/App.config
- examples/Echo.Server/Echo.Server.csproj
- examples/Echo.Server/EchoServerHandler.cs
- examples/Echo.Server/EchoServerSettings.cs
- examples/Echo.Server/Program.cs
- examples/Echo.Server/Properties/AssemblyInfo.cs
This is example of DotNetty client-server application. Server itself can be called using telnet. IMO missing parts are logging handler (which I havent found inside DotNetty implementation) and SSL support which is handled differently than using corellated netty examples.
> Echo client-server example

- .gitignore
- build.cmd
- build.sh
- src/DotNetty.Common/DotNetty.Common.nuspec
Should fix the issue that caused CI to flag #86
> fixed nuget 3.x packaging issues

- src/DotNetty.Codecs/ByteToMessageDecoder.cs
- src/DotNetty.Codecs/DelimiterBasedFrameDecoder.cs
- src/DotNetty.Codecs/Delimiters.cs
- src/DotNetty.Codecs/DotNetty.Codecs.csproj
- src/DotNetty.Codecs/Json/JsonObjectDecoder.cs
- src/DotNetty.Codecs/LengthFieldBasedFrameDecoder.cs
- src/DotNetty.Codecs/LineBasedFrameDecoder.cs
please forgive my newbie git mistake
This should be cleaner and also removed that strange csproj "Strings" thing
> Porting in DelimiterBasedFrameDecoder from Java (redo)

- src/DotNetty.Codecs/CodecException.cs
- src/DotNetty.Codecs/Strings/StringDecoder.cs
- src/DotNetty.Codecs/Strings/StringEncoder.cs
- src/DotNetty.Codecs/UnsupportedMessageTypeException.cs
- src/DotNetty.Common/Deque.cs
- src/DotNetty.Common/ResourceLeakDetector.cs
- src/DotNetty.Transport/Channels/ChannelException.cs
- src/DotNetty.Transport/Channels/ChannelHandlerInvokerUtil.cs
- src/DotNetty.Transport/Channels/ChannelOutboundBuffer.cs
- src/DotNetty.Transport/Channels/DefaultChannelConfiguration.cs
- src/DotNetty.Transport/Channels/DefaultChannelId.cs
- test/DotNetty.Transport.Tests/Channel/DefaulChannelIdTest.cs
Motivation:
Support new versions of .NET, have a core framework that is portable across all .NET platforms.
Modifications:
addressing part of issues reported by portability analyzer
Result:
Easier to introduce .NET Platform compatibility in the future.
> Moving towards .NET Platform compatibility

- src/DotNetty.Common/DotNetty.Common.csproj
- src/DotNetty.Common/Utilities/TimeUtil.cs
- src/DotNetty.Handlers/DotNetty.Handlers.csproj
- src/DotNetty.Handlers/Timeout/IdleState.cs
- src/DotNetty.Handlers/Timeout/IdleStateEvent.cs
- src/DotNetty.Handlers/Timeout/IdleStateHandler.cs
- src/DotNetty.Handlers/Timeout/ReadTimeoutException.cs
- src/DotNetty.Handlers/Timeout/ReadTimeoutHandler.cs
- src/DotNetty.Handlers/Timeout/TimeoutException.cs
- src/DotNetty.Handlers/Timeout/WriteTimeoutException.cs
- src/DotNetty.Handlers/Timeout/WriteTimeoutHandler.cs
- src/DotNetty.Transport/Channels/ChannelDuplexHandler.cs
- src/DotNetty.Transport/DotNetty.Transport.csproj
Implementation Idle connections and timeouts.
Modifications:
Added new handlers:
- IdleStateHandler.cs
- ReadTimeoutHandler
- WriteTimeoutHandler
- ChannelDuplexHandler
Added a new utils class for work with time:
- TimeUtil.cs
> Port idlestatehandler 97

- src/DotNetty.Codecs/MessageToMessageDecoder.cs
- src/DotNetty.Handlers/Tls/TlsHandler.cs
- src/DotNetty.Transport/Bootstrapping/AbstractBootstrap.cs
- src/DotNetty.Transport/Bootstrapping/Bootstrap.cs
Removed some (minor) compiler warnings.
In terms of the CLA, I am a Microsoft intern and I'm not sure exactly how to proceed. Any help would be appreciated. (t-brmilt is my alias)
> Removed some compiler warnings

- src/DotNetty.Handlers/Tls/TlsHandler.cs
Motivation:
TLS start got broken in one of last commits: just connecting to server does not trigger handshake anymore.
Modifications:
reverted server vs client behavior decisions from previous commits.
Result:
Client-side TLS handler will start the handshake once underlying connection is established.
> Fixes TLS initialization

- src/DotNetty.Codecs/Base64/Base64.cs
- src/DotNetty.Codecs/Base64/Base64Decoder.cs
- src/DotNetty.Codecs/Base64/Base64Dialect.cs
- src/DotNetty.Codecs/Base64/Base64Encoder.cs
- src/DotNetty.Codecs/DotNetty.Codecs.csproj
- test/DotNetty.Codecs.Tests/Base64Test.cs
- test/DotNetty.Codecs.Tests/DotNetty.Codecs.Tests.csproj
finish Base64 Encoder and Decode and passed the Netty's unittest.
> port Base64 Encoder/Decoder

- build.cake
- src/DotNetty.Buffers/DotNetty.Buffers.csproj
- src/DotNetty.Codecs.Mqtt/DotNetty.Codecs.Mqtt.csproj
- src/DotNetty.Codecs.Protobuf/DotNetty.Codecs.Protobuf.csproj
- src/DotNetty.Codecs.ProtocolBuffers/DotNetty.Codecs.ProtocolBuffers.csproj
- src/DotNetty.Codecs.Redis/DotNetty.Codecs.Redis.csproj
- src/DotNetty.Codecs/DotNetty.Codecs.csproj
- src/DotNetty.Common/DotNetty.Common.csproj
- src/DotNetty.Handlers/DotNetty.Handlers.csproj
- src/DotNetty.Transport/DotNetty.Transport.csproj
- test/DotNetty.Buffers.Tests/DotNetty.Buffers.Tests.csproj
- test/DotNetty.Codecs.Mqtt.Tests/DotNetty.Codecs.Mqtt.Tests.csproj
- test/DotNetty.Codecs.Protobuf.Tests/DotNetty.Codecs.Protobuf.Tests.csproj
- test/DotNetty.Codecs.ProtocolBuffers.Tests/DotNetty.Codecs.ProtocolBuffers.Tests.csproj
- test/DotNetty.Codecs.Redis.Tests/DotNetty.Codecs.Redis.Tests.csproj
- test/DotNetty.Codecs.Tests/DotNetty.Codecs.Tests.csproj
- test/DotNetty.Common.Tests/DotNetty.Common.Tests.csproj
- test/DotNetty.Handlers.Tests/DotNetty.Handlers.Tests.csproj
- test/DotNetty.Microbench/DotNetty.Microbench.csproj
- test/DotNetty.Microbench/Utilities/CodeTimer.cs
- test/DotNetty.Tests.Common/DotNetty.Tests.Common.csproj
- test/DotNetty.Tests.End2End/DotNetty.Tests.End2End.csproj
- test/DotNetty.Transport.Tests.Performance/DotNetty.Transport.Tests.Performance.csproj
- test/DotNetty.Transport.Tests/DotNetty.Transport.Tests.csproj
Moved all libraries, tests and examples to net45 from net451
> Downgraded to net45

- build.cake
- examples/Discard.Client/Program.cs
- examples/Discard.Server/Program.cs
- examples/Echo.Client/Program.cs
- examples/Echo.Server/Program.cs
- examples/Factorial.Client/Program.cs
- examples/Factorial.Server/Program.cs
- examples/SecureChat.Client/Program.cs
- examples/SecureChat.Server/Program.cs
- examples/Telnet.Client/Program.cs
- examples/Telnet.Server/Program.cs
- src/DotNetty.Buffers/AbstractByteBuffer.cs
- src/DotNetty.Buffers/CompositeByteBuffer.cs
- src/DotNetty.Buffers/PoolArena.cs
- src/DotNetty.Buffers/PoolChunk.cs
- src/DotNetty.Buffers/PooledByteBuffer.cs
- src/DotNetty.Buffers/PooledByteBufferAllocator.cs
- src/DotNetty.Buffers/UnpooledHeapByteBuffer.cs
- src/DotNetty.Common/Concurrency/SingleThreadEventExecutor.cs
- test/DotNetty.Transport.Tests.Performance/Sockets/TcpSocketChannelPerfSpec.cs
- #206
- Fixing examples following move to new csproj to load cert where it's placed
- Fixing STEE behavior when loop crashes
> Add ability to limit buffer pool memory capacity, minor fixes

- src/DotNetty.Handlers/Tls/TlsHandler.cs
> Add new API to retrieve client certificate in X509Certificate2 format

- src/DotNetty.Handlers/Tls/TlsHandler.cs
- src/DotNetty.Transport/Channels/Sockets/AbstractSocketChannel.cs
- test/DotNetty.Buffers.Tests/AbstractByteBufTest.cs
- test/DotNetty.Codecs.Tests/Frame/LengthFieldBasedFrameDecoderTests.cs
- test/DotNetty.Common.Tests/Utilities/HashedWheelTimerTest.cs
> Fixes #225

- src/DotNetty.Transport/Channels/ChannelOutboundBuffer.cs
- src/DotNetty.Transport/Channels/Sockets/TcpSocketChannel.cs
..with buffer list when asynchronously writing to socket in TcpSocketChannel.
extra: release buffer list content more aggressively.
> Fix use after ownership loss issue..

- src/DotNetty.Buffers/ByteBufferUtil.cs
- src/DotNetty.Buffers/CompositeByteBuffer.cs
- src/DotNetty.Buffers/EmptyByteBuffer.cs
- src/DotNetty.Common/ResourceLeakDetector.cs
- test/DotNetty.Buffers.Tests/AbstractCompositeByteBufferTests.cs
- test/DotNetty.Buffers.Tests/ConsolidationTest.cs
- test/DotNetty.Buffers.Tests/EmptyByteBufferTests.cs
1. Leak records target amount and backing off
2. Composite byte buffer copy.
3. Fixed false positive resource leak report sometimes #308 
4. Fixed ByteBufferUtil for string read
5. Removed unused EmptyByteBuffer methods
> ResourceLeakDetector

- src/DotNetty.Codecs/LengthFieldPrepender.cs
> fix long field length truncation

- src/DotNetty.Transport/Channels/ChannelOutboundBuffer.cs
- src/DotNetty.Transport/Channels/Sockets/AbstractSocketByteChannel.cs
- src/DotNetty.Transport/Channels/Sockets/TcpSocketChannel.cs
Linux socket send bugfix minimum change, the old branch is mixed, pull again
fix .net core linux socket bug, use sendasync and fetch max 1024 outbondbuffer entry in linux
.net core issue
https://github.com/dotnet/corefx/issues/23416
https://github.com/dotnet/corefx/issues/23672
> Linux socket send bugfix

- src/DotNetty.Handlers/Logging/LoggingHandler.cs
Make it match Java implementation.
> #329 Mark LoggingHandler as shareable

- src/DotNetty.Buffers/SimpleLeakAwareByteBuffer.cs
- src/DotNetty.Common/ResourceLeakDetector.cs
> Fix false positive resource leak report.

- src/DotNetty.Codecs.Protobuf/ProtobufDecoder.cs
- src/DotNetty.Codecs.Protobuf/ProtobufEncoder.cs
- src/DotNetty.Codecs.ProtocolBuffers/ProtobufDecoder.cs
- src/DotNetty.Codecs.ProtocolBuffers/ProtobufEncoder.cs
Make it match Java implementation.
> #328 Mark ProtobufDecoder and ProtobufEncoder as shareable
