Azure/DotNetty

- src/DotNetty.Codecs.Mqtt/MqttEncoder.cs
- src/DotNetty.Codecs.Mqtt/Packets/SubAckPacket.cs
- src/DotNetty.Codecs.Mqtt/Packets/SubscribePacket.cs
- src/DotNetty.Codecs.Mqtt/Packets/UnsubAckPacket.cs
- src/DotNetty.Codecs.Mqtt/Packets/UnsubscribePacket.cs
- src/DotNetty.Codecs.Mqtt/Signatures.cs
- test/DotNetty.Tests.End2End/End2EndTests.cs
motivation: Fix #5.
Also, adding convenient overload ctors on packets.
> MQTT: fix for incorrect UNSUBSCRIBE decoding / encoding

- DotNetty.sln
- src/DotNetty.Codecs.Mqtt/DotNetty.Codecs.Mqtt.csproj
- src/DotNetty.Codecs.Mqtt/MqttDecoder.cs
- src/DotNetty.Codecs.Mqtt/MqttEncoder.cs
- src/DotNetty.Codecs.Mqtt/Packets/ConnectPacket.cs
- src/DotNetty.Codecs.Mqtt/Packets/PublishPacket.cs
- src/DotNetty.Codecs.Mqtt/Packets/SubscriptionRequest.cs
- src/DotNetty.Codecs.Mqtt/Properties/Friends.cs
- test/DotNetty.Codecs.Mqtt.Tests/DotNetty.Codecs.Mqtt.Tests.csproj
- test/DotNetty.Codecs.Mqtt.Tests/MqttCodecTests.cs
- test/DotNetty.Codecs.Mqtt.Tests/Properties/AssemblyInfo.cs
- test/DotNetty.Codecs.Mqtt.Tests/packages.config
- test/DotNetty.Tests.End2End/End2EndTests.cs
- reworked decoder to use remaining length as an indicator for how many bytes need to be buffered before it makes sense to parse anything beyond the remaining length field in the packet.
- added happy path tests for re-coding for all packet types (#6). 
- bug fixes through testing.
> MQTT codec v1.1

- src/DotNetty.Transport/Channels/Sockets/AbstractSocketChannel.cs
- src/DotNetty.Transport/Channels/Sockets/TcpServerSocketChannel.cs
- src/DotNetty.Transport/Channels/Sockets/TcpSocketChannel.cs
emulates behavior of SocketChannel.isConnected() through addition of StateFlags.Active and respective state changes in AbstractSocketChannel.
> Better IChannel.Active implementation (fix #18)

- build.fsx
- src/SharedAssemblyInfo.cs
Generated nuget packages now contain proper assemblies.
+ changed author to Microsoft Azure
+ dereferencing SslStream-provided state when is not needed anymore in TlsHandler.MediationStream.
> Fixes nuget package creation build target (#23)

- src/DotNetty.Buffers/AbstractByteBuffer.cs
- src/DotNetty.Buffers/CompositeByteBuffer.cs
- src/DotNetty.Buffers/DuplicatedByteBuffer.cs
- src/DotNetty.Buffers/EmptyByteBuffer.cs
- src/DotNetty.Buffers/IByteBuffer.cs
- src/DotNetty.Buffers/SlicedByteBuffer.cs
- src/DotNetty.Buffers/UnpooledHeapByteBuffer.cs
- src/DotNetty.Codecs/CodecException.cs
- src/DotNetty.Codecs/DotNetty.Codecs.csproj
- src/DotNetty.Codecs/UnsupportedMessageTypeException.cs
- src/DotNetty.Common/Utilities/TaskEx.cs
- src/DotNetty.Handlers/Tls/TlsHandler.cs
- src/DotNetty.Transport/Channels/PendingWriteQueue.cs
- src/DotNetty.Transport/Channels/Sockets/AbstractSocketChannel.cs
- src/DotNetty.Transport/DotNetty.Transport.csproj
- test/DotNetty.Buffers.Tests/AbstractByteBufferTests.cs
- test/DotNetty.Tests.End2End/End2EndTests.cs
Fixes #29.
Ported PendingWriteQueue, EmptyByteBuffer and aligned ReadBytes and WriteBytesAsync with other similar methods.
TlsHandler now follows the same scheme (as close as possible with SslStream) as SslHandler in netty.
> TlsHandler with proper WriteAsync/Flush semantics

- build.sh
This should allow the Mono builds to run again, combined with some other fixes I made on TeamCity
> fixed casing issue with Mono build script

- src/DotNetty.Common/Concurrency/AbstractEventExecutor.cs
- src/DotNetty.Common/Concurrency/AbstractScheduledEventExecutor.cs
- src/DotNetty.Common/Concurrency/ExecutorTaskScheduler.cs
- src/DotNetty.Common/Concurrency/ICallable`T.cs
- src/DotNetty.Common/Concurrency/IEventExecutor.cs
- src/DotNetty.Common/Concurrency/SingleThreadEventExecutor.cs
- src/DotNetty.Common/DotNetty.Common.csproj
- src/DotNetty.Common/Timestamp.cs
- src/DotNetty.Common/Utilities/MpscLinkedQueue.cs
- src/DotNetty.Transport/Bootstrapping/ServerBootstrap.cs
- src/DotNetty.Transport/Channels/AbstractChannel.cs
- src/DotNetty.Transport/Channels/ChannelHandlerAdapter.cs
- src/DotNetty.Transport/Channels/PausableChannelEventExecutor.cs
- src/DotNetty.Transport/Channels/Sockets/AbstractSocketChannel.cs
- test/DotNetty.Tests.End2End/DotNetty.Tests.End2End.csproj
- test/DotNetty.Transport.Tests/Channel/Embedded/EmbeddedChannelTest.cs
Motivation:
Better align Event Executors API with netty (Schedule and Submit methods) and remove redundancy in SingleThreadEventExecutor
Modifications:
- changed Schedule method overloads to return `Task` and therefore also renamed it to `ScheduleAsync`
- changed `SubmitAsync` method overloads to work with `Func<T>` -> `Task<T>`
- updated `SingleThreadEventExecutor` to inherit from `AbstractSchedulingEventExecutor`
extras
- added support for cancellation in scheduled tasks
- fixed `ExecutorTaskScheduler.TryDequeue` and related functionality
Results:
- `SingleThreadEventExecutor` is part of Event Executor hierarchy
- It is easier to port / implement functionality that relies on continuations for `ScheduleAsync` or result of `SubmitAsync`'s future.
> aligning Event Executors API

- examples/Echo.Server/Program.cs
- src/DotNetty.Handlers/DotNetty.Handlers.csproj
- src/DotNetty.Handlers/Logging/LogLevel.cs
- src/DotNetty.Handlers/Logging/LogLevelExtensions.cs
- src/DotNetty.Handlers/Logging/LoggingHandler.cs
Port Logging Handler Fixes #38
Motivation:
LoggingHandler  is a must in many situations especially with non-trivial
pipeline composition so it will definitely be ported soon . It actually
provides nice looking bytebuf output + additional log for all the
events.
Modifications:
Added Logging functionality to DotNetty.Handlers project
Modified Echo.Server example project to log the events
Result: Easier to learn DotNetty from output by LoggingHandler
> Port LoggingHandler Fixes #38

- src/DotNetty.Common/Internal/Logging/DefaultEventSource.cs
Motivation:
Guid is necessary for other systems to make a distinction between event.
Modifications:
Guid assigned to the DefaultEventSource.
Result:
We have a Guid now. Yay!
> Assing GUID to event source

- examples/Echo.Client/EchoClientHandler.cs
- examples/Echo.Server/EchoServerHandler.cs
- src/DotNetty.Buffers/AbstractByteBuffer.cs
- src/DotNetty.Buffers/AdvancedLeakAwareByteBuf.cs
- src/DotNetty.Buffers/ByteBufferUtil.cs
- src/DotNetty.Buffers/EmptyByteBuffer.cs
- src/DotNetty.Buffers/IByteBuffer.cs
- src/DotNetty.Buffers/SwappedByteBuffer.cs
- src/DotNetty.Buffers/WrappedByteBuf.cs
I implemented ToString methods in ByteBuffer for user convenience. And modified echo examples.
These methods were implemented in Netty(Java).
```java
// In ByteBuf.java
public abstract String toString(Charset charset);
public abstract String toString(int index, int length, Charset charset);
```
```C#
// In IByteBuffer.cs
string ToString(Encoding encoding);
string ToString(int index, int length, Encoding encoding);
```
```C#
this.buffer.Initialize();
byteBuffer.Duplicate().ReadBytes(this.buffer, 0, byteBuffer.ReadableBytes);
string msg = Encoding.UTF8.GetString(this.buffer);
Console.WriteLine("Received from server: " + msg);
```
```C#
Console.WriteLine("Received from server: " + byteBuffer.ToString(Encoding.Default));
```
> Implemented ToString methods in ByteBuffer for user convenience.

- src/DotNetty.Common/Concurrency/TaskCompletionSource.cs
- src/DotNetty.Transport/Bootstrapping/AbstractBootstrap.cs
- src/DotNetty.Transport/Bootstrapping/Bootstrap.cs
- src/DotNetty.Transport/Channels/DefaultChannelHandlerInvoker.cs
- src/DotNetty.Transport/Channels/DefaultChannelPipeline.cs
Motivation:
Due to misuse of IEventExecutor.SubmitAsync in
DefaultChannelHandlerInvoker and Bootstrap, async operations return future
that is completed after first sync part of operation is through.
Modifications:
DefaultChannelHandlerInvoker and Bootstrap are modified to complete
returned future only after the whole async operation is completed.
Result:
chaining async operations does not result in intermittent failures due to
premature access to channel, errors potentially appearing in later stages
of async operations are also properly reported through failure of the
future.
> Fixes premature completion of async operations (#66)

- src/DotNetty.Buffers/PooledByteBuffer.cs
- test/DotNetty.Buffers.Tests/DotNetty.Buffers.Tests.csproj
- test/DotNetty.Buffers.Tests/PooledBufferAllocatorTests.cs
Motivation:
Fix a bug #71.
Modifications:
Set length property of a PooledByteBuffer in case of a switch of underlying array to unpooled.
Results:
PooledByteBufferAllocator can work with buffers bigger than pooled buffer's original capacity.
> Fixes pooled buffer's AdjustCapacity to properly set the length

- src/DotNetty.Common/ThreadLocalPool.cs
- test/DotNetty.Common.Tests/DotNetty.Common.Tests.csproj
- test/DotNetty.Common.Tests/ThreadLocalPoolTest.cs
resolve #63 
Improved pooling of buffers when a buffer was released in other thread.
Motivation:
When buffer was released in other thread, this buffer couldn't be released. I think that need to release a buffer in other thread for memory effectiveness.
Modifications:
Implement WeakOrderQueue for releasing a buffer that other thread owned.
Result:
When buffer was released in othread thread, owned thread can use this buffer.
> Improved pooling of buffers when a buffer was released in other thread.

- src/DotNetty.Buffers/ByteBufferUtil.cs
- src/DotNetty.Common/Concurrency/AbstractEventExecutor.cs
- src/DotNetty.Common/Concurrency/AbstractScheduledEventExecutor.cs
- src/DotNetty.Common/Concurrency/ActionScheduledAsyncTask.cs
- src/DotNetty.Common/Concurrency/ActionScheduledTask.cs
- src/DotNetty.Common/Concurrency/IEventExecutor.cs
- src/DotNetty.Common/Concurrency/IScheduledRunnable.cs
- src/DotNetty.Common/Concurrency/IScheduledTask.cs
- src/DotNetty.Common/Concurrency/ScheduledAsyncTask.cs
- src/DotNetty.Common/Concurrency/ScheduledTask.cs
- src/DotNetty.Common/Concurrency/StateActionScheduledAsyncTask.cs
- src/DotNetty.Common/Concurrency/StateActionScheduledTask.cs
- src/DotNetty.Common/Concurrency/StateActionWithContextScheduledAsyncTask.cs
- src/DotNetty.Common/Concurrency/StateActionWithContextScheduledTask.cs
- src/DotNetty.Common/DotNetty.Common.csproj
- src/DotNetty.Common/Internal/Logging/InternalLoggerFactory.cs
- src/DotNetty.Common/Utilities/PriorityQueue.cs
- src/DotNetty.Transport/Channels/PausableChannelEventExecutor.cs
- src/DotNetty.Transport/Channels/Sockets/AbstractSocketChannel.cs
- test/DotNetty.Common.Tests/DotNetty.Common.Tests.csproj
- test/DotNetty.Common.Tests/ThreadLocalPoolTest.cs
- test/DotNetty.Common.Tests/Utilities/PriorityQueueTest.cs
- test/DotNetty.Transport.Tests/Channel/Embedded/EmbeddedChannelTest.cs
Motivation:
Allow for less GC when scheduling if Task-based API is not required. Allow for proper cleanup when canceling scheduled task so that associated resources can be cleaned up early.
Modifications:
- Moved out scheduled task implementations from AbstractScheduledEventExecutor
- Introduced IScheduledTask and aligned IScheduledRunnable
- Implemented removal of scheduled task upon its cancellation
Result:
Scheduled tasks that normally never fire (e.g. timeout handling) do not cause resources to be held up unnecessarily in memory for longer period of time if not necessary.
> Adds IEventExecutor.Schedule, proper cancellation of scheduled tasks

- src/DotNetty.Common/Concurrency/SingleThreadEventExecutor.cs
- src/DotNetty.Common/PreciseTimeSpan.cs
- test/DotNetty.Common.Tests/ThreadLocalPoolTest.cs
Fixed polling task from the queue.
Motivation:
Polling task from queue is calculating timeout incorrectly.
Modifications:
Timeout calculation has been fixed
Result:
Event executer works as it should now
> Hotfix: poll task from the queue.

- examples/Echo.Client/Program.cs
- examples/Echo.Server/Program.cs
- src/DotNetty.Buffers/ByteBufferUtil.cs
- src/DotNetty.Buffers/UnpooledHeapByteBuffer.cs
- src/DotNetty.Common/Concurrency/SingleThreadEventExecutor.cs
- src/DotNetty.Handlers/Tls/TlsHandler.cs
- test/DotNetty.Common.Tests/Concurrency/SingleThreadEventExecutorTests.cs
- test/DotNetty.Tests.End2End/DotNetty.Tests.End2End.csproj
- test/DotNetty.Tests.End2End/End2EndTests.cs
Motivation:
Fix up top priority issues to ensure proper working state with recent changes.
Modifications:
- TlsHandler negotiates TLS 1.0+ on server side (#89)
- STEE properly supports graceful shutdown (#7)
- UnpooledHeapByteBuffer.GetBytes honors received index and length (#88)
- Echo E2E test uses length-prefix based framing (#90)
Result:
Setting up DotNetty does not require workarounds for shutdown and hacks to enable negotiation of higher versions of TLS. Tests are passing even with new SslStream behavior.
> Fixes ByteBuffer+Stream integration, TLS neg, STEE Shutdown

- DotNetty.sln
- build.cmd
- build.fsx
- build.sh
- test/DotNetty.Common.Tests/DotNetty.Common.Tests.csproj
- test/DotNetty.Common.Tests/ResourceLeakDetectorTest.cs
- test/DotNetty.Common.Tests/app.config
- test/DotNetty.Tests.Common/app.config
- test/DotNetty.Tests.End2End/DotNetty.Tests.End2End.csproj
- test/DotNetty.Tests.End2End/app.config
- test/DotNetty.Transport.Tests.Performance/DotNetty.Transport.Tests.Performance.csproj
- test/DotNetty.Transport.Tests.Performance/Properties/AssemblyInfo.cs
- test/DotNetty.Transport.Tests.Performance/Sockets/TcpSocketChannelPerfSpec.cs
- test/DotNetty.Transport.Tests.Performance/Utilities/CounterHandlerInbound.cs
- test/DotNetty.Transport.Tests.Performance/Utilities/CounterHandlerOutbound.cs
- test/DotNetty.Transport.Tests.Performance/Utilities/IReadFinishedSignal.cs
- test/DotNetty.Transport.Tests.Performance/Utilities/ManualResetEventSlimReadFinishedSignal.cs
- test/DotNetty.Transport.Tests.Performance/Utilities/ReadFinishedHandler.cs
- test/DotNetty.Transport.Tests.Performance/Utilities/SimpleReadFinishedSignal.cs
- test/DotNetty.Transport.Tests.Performance/Utilities/TaskCompletionSourceFinishedSignal.cs
- test/DotNetty.Transport.Tests.Performance/packages.config
Added NBench support to the build scripts, a sample NBench project, and a port of a benchmark I wrote for Helios that measures duplex end-to-end performance using a realistic encoding pipeline.
> added NBench support + End2End performance spec for TcpSocketChannel

- src/DotNetty.Common/Concurrency/AbstractEventExecutor.cs
- src/DotNetty.Common/Concurrency/AbstractScheduledEventExecutor.cs
- src/DotNetty.Common/Concurrency/IEventExecutor.cs
- src/DotNetty.Common/Concurrency/IWrappedEventExecutor.cs
- src/DotNetty.Common/Concurrency/RunnableScheduledTask.cs
- src/DotNetty.Common/DotNetty.Common.csproj
- src/DotNetty.Transport/Channels/DefaultChannelPipeline.cs
- src/DotNetty.Transport/Channels/Embedded/EmbeddedEventLoop.cs
Motivation:
Improving support for future porting efforts relying on special implementations of `IRunnable` tasks.
Modifications:
- Added `IEventExecutor.Schedule(IRunnable, TimeSpan)` overload
- Extra: cleaning out `IEventExecutor.Unwrap` and related `IWrappedEventExecutor`.
- Extra: fixing synchronization in `DefaultChannelPipeline`'s `Replace` and `DestroyDown` methods.
Result:
Better support for `IRunnable` implementations in execution model.
> Adds Schedule support for IRunnable actions.

- test/DotNetty.Transport.Tests.Performance/DotNetty.Transport.Tests.Performance.csproj
- test/DotNetty.Transport.Tests.Performance/Sockets/TcpSocketChannelInboundOnlyPerfSpec.cs
Uses a basic tcp `Socket` and `NetworkStream` to write to an inbound `TcpServerSocketChannel` to measure read-only performance.
> added inbound only TcpSocketChannel benchmark

- src/DotNetty.Common/DotNetty.Common.csproj
- src/DotNetty.Common/Utilities/AbstractConstant.cs
- src/DotNetty.Common/Utilities/AtomicReference.cs
- src/DotNetty.Common/Utilities/AttributeKey.cs
- src/DotNetty.Common/Utilities/ConstantPool.cs
- src/DotNetty.Common/Utilities/DefaultAttributeMap.cs
- src/DotNetty.Common/Utilities/IAttribute.cs
- src/DotNetty.Common/Utilities/IAttributeMap.cs
- src/DotNetty.Common/Utilities/IConstant.cs
- src/DotNetty.Transport/Bootstrapping/AbstractBootstrap.cs
- src/DotNetty.Transport/Bootstrapping/Bootstrap.cs
- src/DotNetty.Transport/Bootstrapping/ServerBootstrap.cs
- src/DotNetty.Transport/Channels/AbstractChannel.cs
- src/DotNetty.Transport/Channels/AbstractChannelHandlerContext.cs
- src/DotNetty.Transport/Channels/ChannelOption.cs
- src/DotNetty.Transport/Channels/IChannel.cs
- src/DotNetty.Transport/Channels/IChannelHandlerContext.cs
- src/DotNetty.Transport/Channels/IEventLoopGroup.cs
- src/DotNetty.Transport/Channels/MultithreadEventLoopGroup.cs
- test/DotNetty.Transport.Tests.Performance/Sockets/TcpSocketChannelInboundOnlyPerfSpec.cs
- test/DotNetty.Transport.Tests.Performance/Sockets/TcpSocketChannelPerfSpec.cs
Motivation:
Increasing feature parity and dev convenience through addition of arbitrary data assignment on Channel and related API on Bootstrap classes.
Modifications
- Introduced `IAttributeMap`, `IAttribute<T>`, `IConstant` and related impl artifacts.
- Moved `ChannelOption` to common constant codebase
- `AbstractChannel` now inherits from `DefaultChannelMap`
- Reflection-less child optoins config in `ServerBootstrap`
- Extra: minor closure allocation fixes, internal API fixes.
Result:
Attributes can be set on Channels, better code portability in Bootstrap.
> Adds attribute support in Channel, Bootstrap [#78]

- src/DotNetty.Buffers/CompositeByteBuffer.cs
- src/DotNetty.Buffers/PoolSubpage.cs
- src/DotNetty.Common/ThreadLocalPool.cs
- src/DotNetty.Transport/Bootstrapping/AbstractBootstrap.cs
- src/DotNetty.Transport/Channels/AbstractChannel.cs
- src/DotNetty.Transport/Channels/AbstractChannelHandlerContext.cs
- src/DotNetty.Transport/Channels/AdaptiveRecvByteBufAllocator.cs
- src/DotNetty.Transport/Channels/ChannelMetadata.cs
- src/DotNetty.Transport/Channels/ChannelOption.cs
- src/DotNetty.Transport/Channels/DefaultChannelConfiguration.cs
- src/DotNetty.Transport/Channels/DefaultMaxMessagesRecvByteBufAllocator.cs
- src/DotNetty.Transport/Channels/Embedded/EmbeddedChannel.cs
- src/DotNetty.Transport/Channels/FixedRecvByteBufAllocator.cs
- src/DotNetty.Transport/Channels/IChannel.cs
- src/DotNetty.Transport/Channels/IChannelConfiguration.cs
- src/DotNetty.Transport/Channels/IMaxMessagesRecvByteBufAllocator.cs
- src/DotNetty.Transport/Channels/IRecvByteBufAllocatorHandle.cs
- src/DotNetty.Transport/Channels/Sockets/AbstractSocketByteChannel.cs
- src/DotNetty.Transport/Channels/Sockets/AbstractSocketMessageChannel.cs
- src/DotNetty.Transport/Channels/Sockets/TcpServerSocketChannel.cs
- src/DotNetty.Transport/Channels/Sockets/TcpSocketChannel.cs
- src/DotNetty.Transport/DotNetty.Transport.csproj
- test/DotNetty.Common.Tests/ThreadLocalPoolTest.cs
Motivation:
Provides good flexible default while lowering memory consumption on average.
Modifications:
- Synced IRecvByteBufAllocator and relevant parts up to date
- Ported AdaptiveRecvByteBufAllocator
- Extra: properly porting ChannelMetadata
Result:
Process of receiving bytes from network is more configurable and allows for both more conservative and more agressive ingestion.
> Porting adaptive receive buffer prediction

- src/DotNetty.Buffers/DotNetty.Buffers.csproj
- src/DotNetty.Codecs.Mqtt/DotNetty.Codecs.Mqtt.csproj
- src/DotNetty.Codecs/DotNetty.Codecs.csproj
- src/DotNetty.Common/DotNetty.Common.csproj
- src/DotNetty.Handlers/DotNetty.Handlers.csproj
- src/DotNetty.Transport/DotNetty.Transport.csproj
Motivation:
Improve dev exp using DotNetty nuget packages.
Modifications:
- enabled xml-doc output on projects
Result:
xml-docs are packages along binaries in nuget packages.
> Adds xml-doc output/packaging - fixes (#103)

- examples/Echo.Client/Program.cs
- examples/Echo.Server/Program.cs
- src/DotNetty.Handlers/DotNetty.Handlers.csproj
- src/DotNetty.Handlers/Tls/ClientTlsSettings.cs
- src/DotNetty.Handlers/Tls/ServerTlsSettings.cs
- src/DotNetty.Handlers/Tls/TlsHandler.cs
- src/DotNetty.Handlers/Tls/TlsSettings.cs
- test/DotNetty.Handlers.Tests/TlsHandlerTest.cs
- test/DotNetty.Tests.End2End/End2EndTests.cs
Motivation:
Some important SSL Stream settings are hidden in the TlsHandler class
Modifications:
SSLStream is provided by user now via factory method;
TLS settings extended
Results:
More advanced scenarios, like X509 client authentication, are possible to do now
> Exposes SSL Stream and adds more TLS settings

- src/DotNetty.Handlers/Tls/ServerTlsSettings.cs
- src/DotNetty.Handlers/Tls/TlsHandler.cs
Motivation:
SslStream's paramter required client certificate is misleading. In fact in suggests to client to provide the certificate and client may or may not provide it.
If client has not provided the client certificate - it assumes that client is not authenticated from TLS prospective and continues the handshake
Modification:
Expose this setting as a parameter, so that users could set it if needed.
Results:
Allows users to do a client certificate authentication on server.
> Negotiage client certificate

- src/DotNetty.Codecs/Strings/StringDecoder.cs
Marked StringDecoder as Sharable
Motivation:
Can use StringDecoder in a server where you have more than 1 connect to the server. 
This is a bug, since StringEncoder is marked Sharable and there is nothing that stands out as different.
Modifications:
Marked StringDecoder as Sharable
Result:
Sample project like EchoServer and TelnetServer will now be able to receive more than 1 connections.
So will all other code using the StringDecoder
> Bug: StringDecoder not marked as Sharable

- src/DotNetty.Common/Concurrency/AbstractEventExecutor.cs
- src/DotNetty.Common/Concurrency/ExecutionEnvironment.cs
- src/DotNetty.Common/Concurrency/SingleThreadEventExecutor.cs
- src/DotNetty.Common/DotNetty.Common.csproj
Motivation:
In many instances routines may be optimized in a presence of IEventExecutor but it is hard to carry it around everywhere.
Modifications:
- introduced ExecutionEnvironment.TryGetCurrentExecutor which looks up current executor if any.
- modified SingleThreadEventExecutor to set itself as current on its worker thread.
Result:
Executor may be looked up ambiently for optional executor-specific optimizations.
> Allow looking up current executor

- src/DotNetty.Buffers/project.json
- src/DotNetty.Codecs.Mqtt/project.json
- src/DotNetty.Codecs.Protobuf/project.json
- src/DotNetty.Codecs.ProtocolBuffers/project.json
- src/DotNetty.Codecs.Redis/project.json
- src/DotNetty.Codecs/project.json
- src/DotNetty.Common/Concurrency/AbstractEventExecutor.cs
- src/DotNetty.Common/Concurrency/AbstractScheduledEventExecutor.cs
- src/DotNetty.Common/Concurrency/IEventExecutor.cs
- src/DotNetty.Common/Concurrency/IEventExecutorGroup.cs
- src/DotNetty.Common/Concurrency/SingleThreadEventExecutor.cs
- src/DotNetty.Common/project.json
- src/DotNetty.Handlers/project.json
- src/DotNetty.Transport/Channels/AffinitizedEventLoopGroup.cs
- src/DotNetty.Transport/Channels/Embedded/EmbeddedEventLoop.cs
- src/DotNetty.Transport/Channels/IEventLoop.cs
- src/DotNetty.Transport/Channels/IEventLoopGroup.cs
- src/DotNetty.Transport/Channels/MultithreadEventLoopGroup.cs
- src/DotNetty.Transport/Channels/SingleThreadEventLoop.cs
- src/DotNetty.Transport/project.json
Motivation:
In proxy scenarios it is often important to avoid unnecessary switching between event loops while passing traffic from client and server and back.
Modifications:
- Added AffinitizedEventLoopGroup
- introduced IEventExecutor.Parent and IEventLoop.Parent
- better xml-docs for executors and event loops.
Result:
Proxy scenario is better supported out of the box.
> new AffinitizedEventLoopGroup; Refining EE/G and EL/G API and docs

- src/DotNetty.Buffers/AbstractByteBuffer.cs
- src/DotNetty.Buffers/CompositeByteBuffer.cs
- src/DotNetty.Buffers/PoolArena.cs
- src/DotNetty.Buffers/PoolChunk.cs
- src/DotNetty.Buffers/PooledByteBuffer.cs
- src/DotNetty.Buffers/PooledByteBufferAllocator.cs
- src/DotNetty.Buffers/UnpooledHeapByteBuffer.cs
- src/DotNetty.Common/Concurrency/SingleThreadEventExecutor.cs
- test/DotNetty.Transport.Tests.Performance/Sockets/TcpSocketChannelPerfSpec.cs
Motivation:
If pool grows too fast OOM exception may happen.
Modifications:
- add limit on max memory capacity allocated per heap arena, after which allocations are unpooled.
- extra: log exceptions terminating executor loop
Result:
Users have option to limit size of buffer pool.
> Add ability to limit buffer pool memory capacity

- DotNetty.sln
- build.cake
- build.ps1
- examples/Examples.Common/Examples.Common.csproj
- src/DotNetty.Codecs.Protobuf/DotNetty.Codecs.Protobuf.csproj
- src/DotNetty.Common/DotNetty.Common.csproj
- test/DotNetty.Buffers.Tests/DotNetty.Buffers.Tests.csproj
- test/DotNetty.Codecs.Mqtt.Tests/DotNetty.Codecs.Mqtt.Tests.csproj
- test/DotNetty.Codecs.Protobuf.Tests/DotNetty.Codecs.Protobuf.Tests.csproj
- test/DotNetty.Codecs.ProtocolBuffers.Tests/DotNetty.Codecs.ProtocolBuffers.Tests.csproj
- test/DotNetty.Codecs.Redis.Tests/DotNetty.Codecs.Redis.Tests.csproj
- test/DotNetty.Codecs.Tests/DotNetty.Codecs.Tests.csproj
- test/DotNetty.Common.Tests/DotNetty.Common.Tests.csproj
- test/DotNetty.Handlers.Tests/DotNetty.Handlers.Tests.csproj
- test/DotNetty.Microbench/DotNetty.Microbench.csproj
- test/DotNetty.Tests.Common/DotNetty.Tests.Common.csproj
- test/DotNetty.Tests.End2End/DotNetty.Tests.End2End.csproj
- test/DotNetty.Transport.Tests.Performance/DotNetty.Transport.Tests.Performance.csproj
- test/DotNetty.Transport.Tests/DotNetty.Transport.Tests.csproj
1. Microsoft.Extensions.Configuration from 1.1.0 to 1.1.1
2. Microsoft.Extensions.Logging from 1.1.0 to 1.1.1
3. Google.Protobuf from 3.1.0 to 3.2.0
4. Microsoft.NET.Test.Sdk from 15.0.0 preview to 15.0.0
5. XUnit to 2.2.0 release
6. Moq from alpha to 4.7.1
7. NBench from 0.3.4 to 1.0.0
> Follow up .NET tooling/upgraded packages to latest stable version

- src/DotNetty.Handlers/DotNetty.Handlers.csproj
- src/DotNetty.Handlers/Tls/SniHandler.cs
Since the SNI setting was refactored at the last minute in the commit https://github.com/Azure/DotNetty/pull/219/commits/eb3c3f92acfa00e68ac0ccfd091ab3a086e35ccd 
Forgot to update the error message
#219
And since 1 netstandard nuget reference was added in handler project VS added a new section automatically. But moved that new referenece in the already existing itemgroup
> Updated error message in SNI handler and little clean up in handler project

- src/DotNetty.Common/Internal/MacAddressUtil.cs
- src/DotNetty.Transport/Bootstrapping/AbstractBootstrap.cs
- src/DotNetty.Transport/Bootstrapping/Bootstrap.cs
- src/DotNetty.Transport/Bootstrapping/ServerBootstrap.cs
- src/DotNetty.Transport/Channels/DefaultChannelId.cs
```
warn: DotNetty.Transport.Channels.DefaultChannelId[0]
-Dio.netty.processId: {0} (malformed)
dbug: DotNetty.Transport.Channels.DefaultChannelId[0]
-Dio.netty.machineId: X2:X2:X2:X2:X2:X2:X2:X2 (auto-detected)
...
warn: DotNetty.Transport.Bootstrapping.Bootstrap[0]
Unknown channel option: 100
```
```
dbug: DotNetty.Transport.Channels.DefaultChannelId[0]
-Dio.netty.processId: 3959148 (auto-detected)
dbug: DotNetty.Transport.Channels.DefaultChannelId[0]
-Dio.netty.machineId: 00:00:00:00:00:00:00:E0 (auto-detected)
...
warn: DotNetty.Transport.Bootstrapping.ServerBootstrap[0]
Unknown channel option 'SO_BACKLOG' for channel '[id: 0x74d9a761]'
```
The machineId is always `00:00:00:00:00:00:00:E0`(the MAC of Teredo Tunneling Pseudo-Interface), and it's the same as the behavior of the current …
> Do some better log for debug

- CONTRIBUTING.MD
- README.md
GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1
> Fix broken headings in Markdown files

- src/DotNetty.Common/Concurrency/RejectedExecutionException.cs
- src/DotNetty.Common/PreciseTimeSpan.cs
- src/DotNetty.Common/Utilities/ActionTimerTask.cs
- src/DotNetty.Common/Utilities/HashedWheelTimer.cs
- src/DotNetty.Common/Utilities/ITimeout.cs
- src/DotNetty.Common/Utilities/ITimer.cs
- src/DotNetty.Common/Utilities/ITimerTask.cs
- test/DotNetty.Common.Tests/Utilities/HashedWheelTimerTest.cs
Motivation:
It is a common task to manage various timeouts in networking code. Normal high precision timers usually trade performance for precision which is a flexible requirement with timeouts.
Modifications:
- added HashedWheelTimer
- moved RejectedExecutionException to Common.Concurrency
Result:
- users may choose to use HWT in their code to avoid contentions due to frequent timer management.
> Porting HashedWheelTimer

- src/DotNetty.Buffers/AbstractByteBuffer.cs
- src/DotNetty.Buffers/AdvancedLeakAwareByteBuffer.cs
- src/DotNetty.Buffers/ByteBufferUtil.cs
- src/DotNetty.Buffers/CompositeByteBuffer.cs
- src/DotNetty.Buffers/DuplicatedByteBuffer.cs
- src/DotNetty.Buffers/EmptyByteBuffer.cs
- src/DotNetty.Buffers/IByteBuffer.cs
- src/DotNetty.Buffers/PooledHeapByteBuffer.cs
- src/DotNetty.Buffers/SlicedByteBuffer.cs
- src/DotNetty.Buffers/SwappedByteBuffer.cs
- src/DotNetty.Buffers/UnpooledHeapByteBuffer.cs
- src/DotNetty.Buffers/WrappedByteBuf.cs
- src/DotNetty.Common/Utilities/MediumUtil.cs
- test/DotNetty.Buffers.Tests/AbstractByteBufTest.cs
Implemented functions
- https://netty.io/4.0/api/io/netty/buffer/ByteBuf.html#getMedium-int-
- https://netty.io/4.0/api/io/netty/buffer/ByteBuf.html#getUnsignedMedium-int-
- https://netty.io/4.0/api/io/netty/buffer/ByteBuf.html#readMedium--
- https://netty.io/4.0/api/io/netty/buffer/ByteBuf.html#readUnsignedMedium--
- https://netty.io/4.0/api/io/netty/buffer/ByteBuf.html#writeMedium-int-
- https://netty.io/4.0/api/io/netty/buffer/ByteBuf.html#setMedium-int-int-
- https://netty.io/4.0/api/io/netty/buffer/ByteBufUtil.html#swapMedium-int-
Implemented tests
- GetMediumBoundaryCheck1
- GetMediumBoundaryCheck2
- TestSequentialMediumAccess
- TestSequentialMediumLeAccess
- TestSequentialUnsignedMediumAccess
- TestSequentialUnsignedMediumLeAccess
- TestGetMediumAfterRelease
- …
> Implemented GetMedium, GetUnsignedMedium, ReadMedium, ReadUnsignedMedium, WriteMedium, SetMedium

- src/DotNetty.Buffers/AbstractByteBuffer.cs
- src/DotNetty.Buffers/AdvancedLeakAwareByteBuffer.cs
- src/DotNetty.Buffers/ByteBufferUtil.cs
- src/DotNetty.Buffers/CompositeByteBuffer.cs
- src/DotNetty.Buffers/DotNetty.Buffers.csproj
- src/DotNetty.Buffers/DuplicatedByteBuffer.cs
- src/DotNetty.Buffers/EmptyByteBuffer.cs
- src/DotNetty.Buffers/IByteBuffer.cs
- src/DotNetty.Buffers/PooledHeapByteBuffer.cs
- src/DotNetty.Buffers/SlicedByteBuffer.cs
- src/DotNetty.Buffers/SwappedByteBuffer.cs
- src/DotNetty.Buffers/UnpooledHeapByteBuffer.cs
- src/DotNetty.Buffers/WrappedByteBuf.cs
- test/DotNetty.Buffers.Tests/AbstractByteBufTest.cs
The new methods will broken classes which implements `IByteBuffer` and not extends `AbstractByteBuffer`.
This commit also add an new dependency [System.Runtime.CompilerServices.Unsafe](https://www.nuget.org/packages/System.Runtime.CompilerServices.Unsafe) 4.3.0 to `DotNetty.Buffers`.
> Add Float and Zero api for IByteBuffer

- src/DotNetty.Common/Utilities/StringUtil.cs
The current version get `0a` for `0x0A`, but `1A` for `0x1A` for value, and always upper for Prefix. ~The patch make it always output lowercase as netty does.~
***Which one should be used? Upper or Lower?***
> Always use uppercase for HexDump

- src/DotNetty.Handlers/Properties/Friends.cs
- src/DotNetty.Handlers/Timeout/IdleStateEvent.cs
- src/DotNetty.Handlers/Timeout/IdleStateHandler.cs
- src/DotNetty.Handlers/Timeout/ReadTimeoutHandler.cs
- src/DotNetty.Handlers/Timeout/WriteTimeoutHandler.cs
- src/DotNetty.Transport/Channels/Embedded/EmbeddedChannel.cs
- test/DotNetty.Handlers.Tests/IdleStateHandlerTest.cs
* Align API and Test of IdleStateHandler with netty 4.1.15([f9003293...7460d90a](https://github.com/netty/netty/commits/4.1/handler/src/main/java/io/netty/handler/timeout))
* Fix EmbeddedChannel.ReleaseAll crashes when queue is null
* Fix ReadTimeoutHandler don't close channel when timeout
* Change IdleStateHandler.ChannelIdle and WriteTimeoutHandler.WriteTimedOut to virtual
> Realigning API of IdleStateHandler, and some bugfix

- src/DotNetty.Buffers/PooledByteBufferAllocator.cs
`dotNetty.allocator.numHeapArenas` -> `io.netty.allocator.numHeapArenas`
> Change name of prop `numHeapArenas` to match others and logging output

- src/DotNetty.Transport.Libuv/Native/NativeRequest.cs
- src/DotNetty.Transport.Libuv/Native/Tcp.cs
- src/DotNetty.Transport.Libuv/Native/WriteRequest.cs
- src/DotNetty.Transport.Libuv/NativeChannel.cs
1. Fixed client connect resets not propagated to channel pipeline properly
2. Fixed write request wrong buffer count
3. Fixed channel outbound could be null if error occurred
> Libuv channel read issues.

- src/DotNetty.Common/Internal/CompatibleConcurrentQueue.cs
- src/DotNetty.Handlers/DotNetty.Handlers.csproj
- src/DotNetty.Handlers/Flow/FlowControlHandler.cs
- test/DotNetty.Handlers.Tests/Flow/FlowControlHandlerTest.cs
A new ChannelHandler that allows the user to control the flow of messages if upstream handlers emit more than one event for each Read()
Motivation:
Some handlers such as HttpObjectDecoder can emit more than one event per Read()
which leads to problems in downstream handlers that expect only one event and hope
that ChannelConfiguration.AutoRead = false prevents further events being sent while they're
processing the one they've just received.
Modifications:
A new handler called FlowControlHandler that feeds off Read() and AutoRead and acts
as a holding buffer if auto reading gets turned off and more events arrive while auto reading
is off.
Result: 
AutoRead=false semantic can be achieved even with decoders that emit multiple messages per Read()
> FlowControlHandler

- src/DotNetty.Codecs/LengthFieldBasedFrameDecoder.cs
- src/DotNetty.Codecs/LengthFieldPrepender.cs
* Add support for Medium length field in LengthFieldPrepender and LengthFieldBasedFrameDecoder(#252, #349).
* Fix that LengthFieldBasedFrameDecoder cannot decode message with ushort length.
* Prefer ByteOrder from LengthFieldBasedFrameDecoder.GetUnadjustedFrameLength's param instead of instance field.
> Update LengthFieldBasedFrameDecoder, LengthFieldPrepender

- src/DotNetty.Transport.Libuv/LoopExecutor.cs
- src/DotNetty.Transport.Libuv/Native/NativeMethods.cs
- src/DotNetty.Transport.Libuv/Native/ReadOperation.cs
- src/DotNetty.Transport.Libuv/Native/Tcp.cs
- src/DotNetty.Transport.Libuv/Native/WriteRequest.cs
- src/DotNetty.Transport.Libuv/NativeChannel.cs
- src/DotNetty.Transport.Libuv/TcpChannel.cs
- src/DotNetty.Transport/Channels/ChannelOutboundBuffer.cs
- src/DotNetty.Transport/Channels/Sockets/DefaultSocketChannelConfiguration.cs
- src/DotNetty.Transport/Channels/Sockets/TcpSocketChannel.cs
- test/DotNetty.Transport.Libuv.Tests/BufReleaseTests.cs
- test/DotNetty.Transport.Libuv.Tests/EventLoopTests.cs
Pending write buffers released before Libuv write callbacks.
Modifications:
According to Libuv documentation, write requests sent with uv_write will be queued. It is safe to reuse the uv_write_t object only after the callback passed to uv_write is fired.
Made Libuv tcp writes release buffers only after the write callback is called. Aslo avoid write buffer pin/unpin operations if the byte buffers to write already pinned.
Result:
Fix #348 and potentially reduced write pin/unpin operations.
> Fix Libuv write buffers #348

- src/DotNetty.Codecs/LengthFieldPrepender.cs
The max value of a medium 24-bit integer is 2^24 which is 16,777,216 - not 167,772,156 as previously implemented.
> Update condition value for medium int length validation for #252

- src/DotNetty.Buffers/AbstractByteBuffer.cs
- src/DotNetty.Buffers/AbstractByteBufferAllocator.cs
- src/DotNetty.Buffers/ByteBufferUtil.cs
- src/DotNetty.Buffers/EmptyByteBuffer.cs
- src/DotNetty.Buffers/IByteBuffer.cs
- src/DotNetty.Buffers/UnsafeByteBufferUtil .cs
- src/DotNetty.Buffers/WrappedByteBuffer.cs
- src/DotNetty.Buffers/WrappedCompositeByteBuffer.cs
- src/DotNetty.Common/Internal/PlatformDependent.cs
- src/DotNetty.Common/Utilities/CharUtil.cs
- test/DotNetty.Buffers.Tests/AbstractByteBufferTests.cs
- test/DotNetty.Buffers.Tests/EmptyByteBufferTests.cs
- test/DotNetty.Common.Tests/Utilities/HashedWheelTimerTest.cs
- test/DotNetty.Handlers.Tests/Flow/FlowControlHandlerTest.cs
- test/DotNetty.Handlers.Tests/IdleStateHandlerTest.cs
- test/DotNetty.Microbench/Buffers/ByteBufUtilBenchmark.cs
- test/DotNetty.Microbench/DotNetty.Microbench.csproj
- test/DotNetty.Microbench/Program.cs
- test/DotNetty.Tests.End2End/End2EndTests.cs
- test/DotNetty.Transport.Libuv.Tests/ConnectionAttemptTests.cs
- test/DotNetty.Transport.Libuv.Tests/WriteBeforeRegisteredTests.cs
- test/DotNetty.Transport.Tests/Channel/DefaulChannelIdTest.cs
- test/DotNetty.Transport.Tests/Channel/Embedded/EmbeddedChannelTest.cs
- test/DotNetty.Transport.Tests/Channel/Pool/SimpleChannelPoolTest.cs
Motivation:
Implement commonly used string-based operations (originally Netty CharSequence) for byte buffers.
Modifications:
Added read/write/get/set strings methods to byte buffers.
Also reduced unsafe pin/unpins for byte operations.
Result:
String-based operations are supported in DotNetty
> Buffer read/write/get/set strings.

- src/DotNetty.Buffers/AbstractByteBuffer.cs
- src/DotNetty.Buffers/AbstractByteBufferAllocator.cs
- src/DotNetty.Buffers/ThrowHelper.cs
- src/DotNetty.Buffers/UnsafeByteBufferUtil .cs
- src/DotNetty.Common/Internal/PlatformDependent.cs
- src/DotNetty.Common/Internal/PlatformDependent0.cs
- test/DotNetty.Microbench/Buffers/ByteBufferBenchmark.cs
- test/DotNetty.Microbench/Buffers/PooledByteBufferBenchmark.cs
- test/DotNetty.Microbench/Buffers/UnpooledByteBufferBenchmark.cs
- test/DotNetty.Microbench/DotNetty.Microbench.csproj
#371 Unsafe unaligned
#380 ThrowHelper
Added BenchmarkDotNet InliningDiagnoser
@yyjdelete I have changed all ThrowHelper not to do ldstr, you can test it out.
> InliningDiagnoser/Unsafe unaligned.

- src/DotNetty.Transport/Channels/Sockets/AbstractSocketChannel.cs
- src/DotNetty.Transport/Channels/Sockets/TcpSocketChannel.cs
This PR fixes 2 issues - 
1. If Socket.ConnectAsync returns synchronously, then we cannot assume that the connection succeeded. The connection needs to be validated. 
2. When Fulfilling the connect promise FireChannelActive should be called irrespective of whether the Promise is set. This is because the Promise is set only if the Socket.ConnectAsync returns asynchronously.
> Fix socket connecting synchronously

- src/DotNetty.Common/Concurrency/SingleThreadEventExecutor.cs
- src/DotNetty.Common/FastThreadLocal.cs
- src/DotNetty.Common/Internal/AppendableCharSequence.cs
- src/DotNetty.Common/Internal/ConcurrentCircularArrayQueue.cs
- src/DotNetty.Common/Internal/Logging/AbstractInternalLogger.cs
- src/DotNetty.Common/Internal/Logging/FormattingTuple.cs
- src/DotNetty.Common/Internal/Logging/IInternalLogger.cs
- src/DotNetty.Common/Internal/Logging/InternalLogLevel.cs
- src/DotNetty.Common/Internal/Logging/MessageFormatter.cs
- src/DotNetty.Common/Internal/MpscArrayQueue.cs
- src/DotNetty.Common/Internal/RefArrayAccessUtil.cs
- src/DotNetty.Common/Internal/SpscLinkedQueue.cs
- src/DotNetty.Common/InternalThreadLocalMap.cs
- src/DotNetty.Common/ThreadDeathWatcher.cs
- src/DotNetty.Common/Utilities/ByteProcessor.cs
- src/DotNetty.Common/Utilities/HashedWheelTimer.cs
- src/DotNetty.Common/Utilities/ITimeout.cs
- src/DotNetty.Common/Utilities/ITimer.cs
- src/DotNetty.Common/Utilities/ReferenceCountUtil.cs
This is a progressive commit towards completing #386.
No code changes have been made, only changes to comments.
These changes to comments include:
- Transforming `{@link Symbol}` occurrences to `<see cref="Symbol"/>`
- Updating Java example code in comments with C# equivalents
- Translating/removing comments that do not apply to .NET generally
- Removing Netty-specific comments that do not yet apply to this port
- Various grammar and typo corrections
Files whose comments did not contain javadoc syntax, or already appeared to have been converted to xmldoc, were not changed.
> Convert javadoc to C# xmldoc in the DotNetty.Common project

- src/DotNetty.Common/Concurrency/AbstractEventExecutor.cs
- src/DotNetty.Common/Concurrency/AbstractEventExecutorGroup.cs
- src/DotNetty.Common/Concurrency/AbstractExecutorService.cs
- src/DotNetty.Common/Concurrency/IEventExecutor.cs
- src/DotNetty.Common/Concurrency/IEventExecutorGroup.cs
- src/DotNetty.Common/Concurrency/IExecutor.cs
- src/DotNetty.Common/Concurrency/IExecutorService.cs
- src/DotNetty.Common/Concurrency/IScheduledExecutorService.cs
- src/DotNetty.Transport.Libuv/DispatcherEventLoop.cs
- src/DotNetty.Transport.Libuv/DispatcherEventLoopGroup.cs
- src/DotNetty.Transport.Libuv/EventLoop.cs
- src/DotNetty.Transport.Libuv/EventLoopGroup.cs
- src/DotNetty.Transport.Libuv/WorkerEventLoop.cs
- src/DotNetty.Transport.Libuv/WorkerEventLoopGroup.cs
- src/DotNetty.Transport/Channels/AffinitizedEventLoopGroup.cs
- src/DotNetty.Transport/Channels/Embedded/EmbeddedEventLoop.cs
- src/DotNetty.Transport/Channels/IEventLoop.cs
- src/DotNetty.Transport/Channels/IEventLoopGroup.cs
- src/DotNetty.Transport/Channels/MultithreadEventLoopGroup.cs
- src/DotNetty.Transport/Channels/SingleThreadEventLoop.cs
This PR aims to make reading `netty`'s code easier by aligning most of the executors with the counterparts in `java.util.concurrent` package.
> Align with java executor services

- build.cake
The name of the .sln file does not match the filesystem name because of the case: this prevents the build to succeed in Linux systems.
> Fixed typo in .sln

- build.cake
- src/DotNetty.Common/Utilities/HashedWheelTimer.cs
https://github.com/Azure/DotNetty/blob/dev/src/DotNetty.Common/Utilities/HashedWheelTimer.cs#L356
It will add the timeout to the next of the right bucket, the timeout will be executed after one more tick.
Code in netty:
https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/HashedWheelTimer.java#L508
Also update the build.cake to support the configuration parameter.
> Transfer timeouts to the right buckets and update the build.cake to support the configuration parameter
